user1 = User.create(name: 'Teahead')
user2 = User.create(name: 'Tea King')
Game.create(user_id: user1.id, score: 1259)
Game.create(user_id: user2.id, score: 1386)
Game.create(user_id: user1.id, score: 1423)
Game.create(user_id: user2.id, score: 1149)
